/**
 * java-util: Java Utilities
 * <p>
 * This module-info.java is for IDE (IntelliJ) recognition only.
 * The actual module-info.class in the JAR is generated by moditect.
 * </p>
 *
 * @author John DeRegnaucourt (jdereg@gmail.com)
 *         <br>
 *         Copyright (c) Cedar Software LLC
 *         <br><br>
 *         Licensed under the Apache License, Version 2.0 (the "License");
 *         you may not use this file except in compliance with the License.
 *         You may obtain a copy of the License at
 *         <br><br>
 *         <a href="http://www.apache.org/licenses/LICENSE-2.0">License</a>
 *         <br><br>
 *         Unless required by applicable law or agreed to in writing, software
 *         distributed under the License is distributed on an "AS IS" BASIS,
 *         WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *         See the License for the specific language governing permissions and
 *         limitations under the License.
 */
module com.cedarsoftware.util {
    requires java.sql;
    requires static java.xml;

    exports com.cedarsoftware.util;
    exports com.cedarsoftware.util.cache;
    exports com.cedarsoftware.util.convert;
    exports com.cedarsoftware.util.geom;
}
